# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Saeid Noroozi
title: Software Engineer
email: s.noroozi.cs@gmail.com
phone: +98 - 912 861 2696
website: https://s-noroozi-cs.github.io

# Dark Mode (true/false/never)
darkmode: true

github_username:  s-noroozi-cs
linkedin_username: saeid-noroozi



# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Working as a <mark>Software Engineer</mark> for 10+ years, makes Saeid expert engineer in software industry. He is <mark>quite keen</mark> on learning new technologies and innovation. Besides, his experience is full of architectural challenges such as <mark>performance tuning, scaling, failover</mark>, etc.  He has great experiences in <mark>CI / CD and automation</mark>. 
  
  <a href="documents/cv-saeid-noroozi.pdf" target="_blank">Download My CV</a>
  
  Skills
    - Java
    - Microservices
    - Spring-boot
    - Apache Kafka
    - Docker
    - Apache Cassandra
    - Jenkins & GitLab CI-CD
    - Linux Shell Scripting
    - SQL

content:
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Shamsipour Technical and Vocational University
        sub_title: BS, Software Enginnering
        caption: 2006 - 2010
        quote: >
          Shamsipour Technical and Vocational College is one of the higher education centers in Tehran, Iran. Before the 1979 revolution, it was being called "Tehran Institute of Technology", which changed to "[Martyr] Shamsipour Technical University " after Hossein Ali Shamsipour.
        description: | # this will include new lines to allow paragraphs
          I surveied multiple and different face recognition algorithms. My professor customized CVQ algorithm as face recognition algorithm. I improved it with neural networn( train and recalculating to decrese wrong rate), Also implemnented it with Java (Standard Edition) and tested it with ORL, MIT, Yale face data sets.
  - title: Publication
    layout: text
    content: | 
         - A Novel Approach based on CVQ Technique for Face Recognition
           - 3rd International Conference on Signal Acquisition and Processing
           - Feb 26 2011
           - <a href="documents/2011_ICSAP_A-Novel-Approach-based-on-CVQ-Technique-for-Face-Recognition.pdf" target="_blank">PDF - Download Link</a>

  - title: Instructor, Consultant 
    layout: text
    content: | 
          - Apache Kafka
           - Scope: Instructing and Consultanting
           - Audience: Developer and DevOps
           - Date: July-September 2022
           - Location: Tehran, Iran
           - <a href="https://github.com/s-noroozi-cs/kafka-training" target="_blank">GitHub Repository</a>
           
         - GitLab CI - CD
           - Scope: Introduction and Configuration
           - Audience: DevOps 
           - Date: May-June 2022
           - Location: Tehran, Iran
           - <a href="https://www.linkedin.com/in/saeid-noroozi" target="_blank">Topics Detail</a> 
         
         - Apache Kafka
           - Scope: Introduction, Managing and Administration
           - Audience: Developer and DevOps 
           - Date: March-May 2021
           - Location: Tehran, Iran
           - <a href="documents/isc-apache-kafka.pdf" target="_blank">PDF - Download Link</a>
           - <a href="documents/apache-kafka-useful-articles.txt" target="_blank">Reference Articles Link</a>
        

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
       My hobbies are: 
       
         - Reading books, My favorite authors
           - <a href="https://en.wikipedia.org/wiki/Irvin_D._Yalom" target="_blank">Irvin D. Yalom</a>
           - <a href="https://en.wikipedia.org/wiki/Hermann_Hesse" target="_blank">Hermann Hesse</a>
           - <a href="https://en.wikipedia.org/wiki/Jostein_Gaarder" target="_blank">Jostein Gaarder</a>
           - <a href="https://en.wikipedia.org/wiki/Cal_Newport" target="_blank">Cal Newport</a>
           - <a href="https://en.wikipedia.org/wiki/Rolf_Dobelli" target="_blank">Rolf Dobelli</a>
           - <a href="https://en.wikipedia.org/wiki/Coders_at_Work" target="_blank">Peter Seibel</a>
           - <a href="https://en.wikipedia.org/wiki/Peter_Thiel#Zero_to_One" target="_blank">Peter Thiel</a>
           - <a href="https://en.wikipedia.org/wiki/Rumi" target="_blank">Jal훮l ad-D카n Mohammad R큰m카</a>
         - Watch Documentary and Drama Movies         
         - Sports
           - Walking
           - Cycling
           - Mountaineering
           - Swimming

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
