# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Saeid Noroozi
title: Backend Software Engineer
email: s.noroozi.cs@gmail.com
# email_title: Email (Email title override)
phone: +98 - 912 861 2696
# phone_title: Phone (Phone title override)
website: https://s-noroozi-cs.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

github_username:  s-noroozi-cs


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Working as a <mark>java developer</mark> for 9+ years, makes Saeid expert engineer in software industry. He is quite keen on learning new technologies and innovation. Besides, his experience is full of architectural challenges such as <mark>performance tuning, scaling, failover</mark>, etc.  He has great experiences in <mark>CI / CD and automation</mark>.

content:
  - title: Skills
    layout: list
    content:
      - title: Java
      - title: Microservices
      - title: Spring-boot
      - title: Apache Kafka
      - title: Docker
      - title: Jenkins
      - title: Unix / Linux Shell-Scripting
      - title: SQL        
  - title: Education
    layout: list
    content:
      - layout: right
        title: Technical and Vocational University - Shamsipour Technical College
        sub_title: BS, Software Enginnering
        caption: 2005 - 2010

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
       My hobbies are: 
       
         - Reading books, My favorite authors
           - <a href="https://en.wikipedia.org/wiki/Irvin_D._Yalom">Irvin D. Yalom</a>
           - <a href="https://en.wikipedia.org/wiki/Jostein_Gaarder">Jostein Gaarder</a>
           - <a href="https://en.wikipedia.org/wiki/Cal_Newport">Cal Newport</a>
           - <a href="https://en.wikipedia.org/wiki/Rolf_Dobelli">Rolf Dobelli</a>
           - <a href="https://en.wikipedia.org/wiki/Coders_at_Work">Peter Seibel</a>
           - <a href="https://en.wikipedia.org/wiki/Rumi">Jal훮l ad-D카n Mohammad R큰m카</a>
         <br/>
         - Watch Documentary and Drama Movies
         <br/>
         - Sports
           - Walking
           - Cycling
           - Mountaineering
           - Swimming

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
